import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import CarTable from "@/components/Table";
// import { PDFViewer } from "@react-18-pdf/renderer";
// import Pdf from "@/components/PDF/Pdf";
import { useState } from "react";
import { Document, Page, PDFViewer, Text } from "@react-pdf/renderer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <PDFViewer>
            <Document>
              <Page>
                <Text>Hola</Text>
              </Page>
            </Document>
          </PDFViewer>
        </div>
      </main>
    </>
  );
}


ReactDOM.render(<Home />, document.getElementById('root'))